version: '3.0'
services:
  pg_store:
    image: docker.bale.ai/bot/balepostgres:1.6.0
    container_name: pg_store
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123456
      - POSTGRES_DB=my_db
      - TZ=Asia/Tehran
    volumes:
      - /home/docker/volumes/pg_store/postgres/:/var/lib/postgresql/data/
    ports:
      - "5443:5432"
  store_customer_bot:
    image: docker.bale.ai/money/store_customer_bot:0.0-1
    container_name: store_customer_bot
    environment:
      #   PostgreSQL Config
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123456
      - POSTGRES_DB=my_db
      - POSTGRES_HOST=pg_store
      - POSTGRES_PORT=5432
      #   Config
      - BASE_URL=https://tapi.bale.ai/
      - BASE_FILE_URL=https://tapi.bale.ai/file/
      - CUSTOMER_TOKEN=ctoken
      - WEB_HOOK_IP=0.0.0.0
      - WEB_HOOK_PORT=80
      - WEB_HOOK_DOMAIN=https://testwebhook.bale.ai
      - WEB_HOOK_PATH=/ctoken
      #   Log config
      - USE_GRAYLOG=0
      - SOURCE=store_customer_source_bot
      - GRAYLOG_HOST=127.0.0.1
      - GRAYLOG_PORT=12201
      - LOG_LEVEL=10
      - LOG_FACILITY_NAME=store_bot_facility
      - MONITORING_HASH=cabb3f498ac5a037f669f658f1be08c3
    ports:
      - "9002:80"
    restart: always # use always
    depends_on:
      - pg_store
  store_seller_bot:
    image: docker.bale.ai/money/store_seller_bot:0.0-1
    container_name: store_seller_bot
    environment:
      #   PostgreSQL Config
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123456
      - POSTGRES_DB=my_db
      - POSTGRES_HOST=pg_store
      - POSTGRES_PORT=5432
      #   Config
      - BASE_URL=https://tapi.bale.ai/
      - BASE_FILE_URL=https://tapi.bale.ai/file/
      - SELLER_TOKEN=stoken
      - WEB_HOOK_IP=0.0.0.0
      - WEB_HOOK_PORT=80
      - WEB_HOOK_DOMAIN=https://testwebhook.bale.ai
      - WEB_HOOK_PATH=/stoken
      #   Log config
      - USE_GRAYLOG=0
      - SOURCE=store_seller_source_bot
      - GRAYLOG_HOST=127.0.0.1
      - GRAYLOG_PORT=12201
      - LOG_LEVEL=10
      - LOG_FACILITY_NAME=store_bot_facility
      - MONITORING_HASH=cabb3f498ac5a037f669f658f1be08c3
    ports:
      - "9003:80"
    restart: always # use always
    depends_on:
      - pg_store
